name: 'Make build decision'
description: 'Decide whether to execute a build or not'

inputs:
  no-bump-message:
    description: 'Partial commit message that indicates build should not be executed'
    required: true

outputs:
  decision:
    description: "Should a build be executed"
    value: ${{ steps.decide.outputs.decision }}

runs:
  using: "composite"
  steps:
    - id: get-execution-context
      uses: ./.github/actions/get-execution-context

    - shell: bash
      name: summary
      run: |
        echo "Head commit message: ${{ github.event.head_commit.message }}" >> $GITHUB_STEP_SUMMARY
        echo "No bump message: ${{ inputs.no-bump-message }}" >> $GITHUB_STEP_SUMMARY
        echo "Head commit contains no bump message: ${{ contains(github.event.head_commit.message, inputs.no-bump-message) }}" >> $GITHUB_STEP_SUMMARY

    - id: decide
      shell: bash
      run: |
        if [[ ${{ steps.get-execution-context.outputs.is-default-branch == 'true' && contains(github.event.head_commit.message, inputs.no-bump-message) }} ]]
        then
          echo "decision=skip" >> $GITHUB_OUTPUT
        else
          echo "decision=build" >> $GITHUB_OUTPUT
        fi
