name: 'Make build decision'
description: 'Decide whether to execute a build or not'

inputs:
  no-bump-message:
    description: 'Partial commit message that indicates build should not be executed'
    required: true

outputs:
  should-build:
    description: "Should a build be executed"
    value: ${{ steps.check.outputs.should_build }}

runs:
  using: "composite"
  steps:
    - id: get-execution-context
      uses: ./.github/actions/get-execution-context

    - shell: bash
      run: |
        echo "${{ steps.get-execution-context.outputs.is-default-branch }}" >> $GITHUB_STEP_SUMMARY
        echo "${{ inputs.no-bump-message }}" >> $GITHUB_STEP_SUMMARY