name: 'Make build decision'
description: 'Decide whether to execute a build or not'

inputs:
  no-bump-message:
    description: 'Partial commit message that indicates build should not be executed'
    required: true

outputs:
  decision:
    description: "Should a build be executed"
    value: ${{ steps.decide.outputs.decision }}

runs:
  using: "composite"
  steps:
    - id: get-execution-context
      uses: ./.github/actions/get-execution-context

    - shell: bash
      id: get-head-commit
      name: summary
      run: |
        echo "No bump message: ${{ inputs.no-bump-message }}" >> $GITHUB_STEP_SUMMARY
        echo "HEAD_COMMIT_MESSAGE=${{ github.event.head_commit.message || github.event.workflow_run.head_commit.message }}" >> $GITHUB_ENV
        echo "Head commit message: ${{ env.HEAD_COMMIT_MESSAGE }}" >> $GITHUB_STEP_SUMMARY
        echo "Head commit contains no bump message: ${{ contains(env.HEAD_COMMIT_MESSAGE, inputs.no-bump-message) }}" >> $GITHUB_STEP_SUMMARY
        echo "head_commit_message=${{ env.HEAD_COMMIT_MESSAGE }}" >> $GITHUB_OUTPUT

    - id: decide
      shell: bash
      run: |
        if [[ ${{ steps.get-execution-context.outputs.is-default-branch == 'true' && contains(steps.get-head-commit.outputs.head_commit_message, inputs.no-bump-message) }} == 'true' ]]
        then
          echo "decision=skip" >> $GITHUB_OUTPUT
        else
          echo "decision=build" >> $GITHUB_OUTPUT
        fi
