name: 'Is Default Branch'
description: 'Is the workflow running on the default branch'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "Current branch: ${{ github.ref }}" >> $GITHUB_STEP_SUMMARY
        echo "Default branch: ${{ format('refs/heads/{0}', github.event.repository.default_branch) }}" >> $GITHUB_STEP_SUMMARY
        echo "Is default branch: ${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}" >> $GITHUB_STEP_SUMMARY