name: Check if default branch

on: 
  workflow_call:    

jobs:
  dummy-build:
    name: Execute a dummy build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout
      
      - uses: ./.github/actions/make-build-decision
        name: Make build decision
        id: make-build-decision
      
      - if: steps.make-build-decision.outputs.should-build == 'true'
        run: echo "Proceed with build!!" >> $GITHUB_STEP_SUMMARY
      
      - if: steps.make-build-decision.outputs.should-build == 'false'
        run: echo "Don't proceed with build." >> $GITHUB_STEP_SUMMARY