name: Check if default branch
on: 
  workflow_call:    

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout
      - uses: ./.github/actions/is-default-branch
        name: Check branch