name: Test reusable workflow

on: 
  workflow_run:
    workflows: [ Fake Release ]
    types: [ completed ]
    branches: [ main ]
  push:
    branches:
      - main
  pull_request:


jobs:
  check-if-default-branch:
    name: Check if default branch
    uses: ./.github/workflows/check-if-default-branch.yml

  dummy-build:
    name: Dummy build
    uses: ./.github/workflows/dummy-build.yml
    with:
      no-bump-message: '#none'